### ISSUE TITLE
Pool can contain the same connection multiple times ... somehow

### ISSUE THREAD

**Issue by Sebmaster** [christkv/mongodb-core#100]
So we've just tried upgrading from mongoose 3.8 to 4.x and we're getting the classic
```
(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Socket.addListener (events.js:252:17)
  at Socket.Readable.on (_stream_readable.js:673:33)
  at Socket.once (events.js:278:8)
  at Socket.unref (net.js:1029:10)
  at [object Object].Connection.destroy (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:449:23)
  at /app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:189:7
  at Array.forEach (native)
  at [object Object].Pool.destroy (/app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:182:15)
  at [object Object].Server.destroy (/app/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:1073:31)
  at [object Object].Server.close (/app/node_modules/mongoose/node_modules/mongodb/lib/server.js:398:17)
  at [object Object].Db.close (/app/node_modules/mongoose/node_modules/mongodb/lib/db.js:357:19)
  at NativeConnection.doClose (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:222:11)
  at NativeConnection.Connection._close (/app/node_modules/mongoose/lib/connection.js:566:12)
  at /app/node_modules/mongoose/lib/connection.js:537:11
  at new Promise.ES6 (/app/node_modules/mongoose/lib/promise.js:45:3)
  at NativeConnection.Connection.close (/app/node_modules/mongoose/lib/connection.js:536:10)
  at /app/node_modules/mongoose/lib/index.js:256:10
  at Array.forEach (native)
  at Mongoose.disconnect (/app/node_modules/mongoose/lib/index.js:255:20)
```

I've overwritten `EventEmitter.prototype.on` and can see that there're 2 `connect` event listeners are added to a Socket related to mongo right at the start of the application. Then there're no additional ones while it's running and at the end there'll be a whole lot of `connect` listeners appended again with the above stacktrace (all of them the same - seemingly in `unref`).

I've now ended up logging `connections.length, _.uniq(connections).length` in `Pool.prototype.destroy` and I'm getting a result of `41, 4`, which makes it seem like the same connection is added multiple times to the pool. I have no idea how that can be yet though. (4 is our poolSize in that case).

Any ideas how to dig into this further? I'll try to get to the bottom of this, just seems like you'd have a better grasp on where that might come from.

Version info is:
```
─┬ mongoose@4.4.19
  └─┬ mongodb@2.1.18
    └── mongodb-core@1.3.18 
```
I'm pretty sure I tried it with 2.1.20 as well though, with the same results, but I can try again if there's been a recent fix in that area.

**Comment by nbrachet** [comment]
Which version of mongo are you running against? If < 3.2 then try the latest version of mongodb-core (on the 1.3 branch, past 8149914) and see if that addresses your issue.

**Comment by Sebmaster** [comment]
Sweet, that gives me 4 connections when closing :+1:
