### ISSUE TITLE
getting TypeError: value.id.copy is not a function error 

### ISSUE THREAD

**Issue by hbakhtiyor** [christkv/mongodb-core#122]
"version": "2.0.6"

stack
```
TypeError: value.id.copy is not a function
    at serializeObjectId (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:252:14)
    at serializeInto (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:571:17)
    at serializeObject (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:291:18)
    at serializeInto (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:731:17)
    at serializeObject (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:291:18)
    at serializeInto (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:731:17)
    at serializeObject (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:291:18)
    at serializeInto (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:577:17)
    at serializeObject (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:291:18)
    at serializeInto (/var/www/demo-service/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:731:17)

```

**Comment by christkv** [comment]
do you have mixed driver versions and thus using the wrong version of an ObjectId with the driver ?

**Comment by christkv** [comment]
the code is

  // Write the objectId into the shared buffer
  if(typeof value.id == 'string') {
    buffer.write(value.id, index, 'binary')
  } else {
    value.id.copy(buffer, index, 0, 12);
  }

you getting an error means either id is null or does not contain a copy meaning it's not a buffer.

**Comment by hbakhtiyor** [comment]
i use only `2.2.4` version of `mongodb` native driver.
the driver uses with these dependencies:
`bson: 0.5.2`
`mongodb-core: 2.0.6`


```js
  // Write the objectId into the shared buffer
  console.log(value, typeof value);
  console.log(value.id, typeof value.id);
  if(typeof value.id == 'string') {
    buffer.write(value.id, index, 'binary')
  } else {
    value.id.copy(buffer, index, 0, 12);
  }
```

output

```
{ _bsontype: 'ObjectID',
  id: 
   { '0': 86,
     '1': 88,
     '2': 91,
     '3': 171,
     '4': 102,
     '5': 16,
     '6': 78,
     '7': 115,
     '8': 0,
     '9': 253,
     '10': 134,
     '11': 223 } } 'object'
{ '0': 86,
  '1': 88,
  '2': 91,
  '3': 171,
  '4': 102,
  '5': 16,
  '6': 78,
  '7': 115,
  '8': 0,
  '9': 253,
  '10': 134,
  '11': 223 } 'object'
```

**Comment by christkv** [comment]
can you write a simple node.js script that reproduces this issue as this points to your ObjectId being corrupt for some reason making me think something else in your code is causing it.

**Comment by hbakhtiyor** [comment]
i used above exact versions of the dependencies in [the demo](https://gist.github.com/hbakhtiyor/d0a2bd5856b56936174a4232a06162e8
), but not get any errors.

my project worked well, but recently got the error during running acceptance tests at CI, 
i use [typeodm](https://github.com/pleerock/typeodm) in my project.
the flow of getting documents by ids, i get array of string ids from request query param and create ObjectId using [this util](https://github.com/pleerock/typeodm/blob/master/src/util/OdmUtils.ts#L20) and build query criteria for find method of mongodb.

**Comment by christkv** [comment]
can you provide an example of a string that causes this. the printout you provided shows what is a corrupt id value (as in it should be a buffer if it's not a string). without the example value passed to the ObjectId constructor that caused this I cannot know what the problem is.

**Comment by hbakhtiyor** [comment]
the output:

```
debug: called get entities endpoint with query param 
{ excludeIds: [ '56585bab66104e7300fd86df' ] }
debug: finding entities with the built criteria and options 
{ criteria: 
   { '$or': 
      [ { _id: 
           { '$nin': 
              [ { _bsontype: 'ObjectID',
                  id: 
                   { '0': 86,
                     '1': 88,
                     '2': 91,
                     '3': 171,
                     '4': 102,
                     '5': 16,
                     '6': 78,
                     '7': 115,
                     '8': 0,
                     '9': 253,
                     '10': 134,
                     '11': 223 } } ] } } ] },
  options: { limit: 100, project: { organization: false } } }
error: error during find and count entities by a given filter 
{ filter: { excludeIds: [ '56585bab66104e7300fd86df' ] },
  error: {...} }

```

**Comment by christkv** [comment]
this is the constructor for ObjectId

```js
/**
* Create a new ObjectID instance
*
* @class
* @param {(string|number)} id Can be a 24 byte hex string, 12 byte binary string or a Number.
* @property {number} generationTime The generation time of this ObjectId instance
* @return {ObjectID} instance of ObjectID.
*/
var ObjectID = function ObjectID(id) {
  // Duck-typing to support ObjectId from different npm packages
  if(id instanceof ObjectID) return id;
  if(!(this instanceof ObjectID)) return new ObjectID(id);

  this._bsontype = 'ObjectID';

  var __id = null;
  var valid = ObjectID.isValid(id);

  // Throw an error if it's not a valid setup
  if(!valid && id != null){
    throw new Error("Argument passed in must be a single String of 12 bytes or a string of 24 hex characters");
  } else if(valid && typeof id == 'string' && id.length == 24) {
    return ObjectID.createFromHexString(id);
  } else if(id == null || typeof id == 'number') {
    // convert to 12 byte binary string
    this.id = this.generate(id);
  } else if(id != null && id.length === 12) {
    // assume 12 byte string
    this.id = id;
  } else if(id != null && id.toHexString) {
    // Duck-typing to support ObjectId from different npm packages
    return id;
  }

  if(ObjectID.cacheHexString) this.__id = this.toHexString();
};
```

Can you add statements to see what branch it's taking when creating the instance. Might help us track down why you are getting a garbage ObjectId

**Comment by christkv** [comment]
you can find the code under the bson module. Also please post the version of the bson lib

**Comment by hbakhtiyor** [comment]
> mongodb: 2.2.4
bson: 0.5.2
mongodb-core: 2.0.6

```js
var ObjectID = function ObjectID(id) {
  console.log(id, typeof id, "instanceof ObjectID?", id instanceof ObjectID, "instanceof Buffer?", id instanceof Buffer, "caller", ObjectID.caller);
  // Duck-typing to support ObjectId from different npm packages
  if(id instanceof ObjectID) return id;
  if(!(this instanceof ObjectID)) return new ObjectID(id);

  this._bsontype = 'ObjectID';

  var __id = null;
  var valid = ObjectID.isValid(id);

  // Throw an error if it's not a valid setup
  if(!valid && id != null){
    throw new Error("Argument passed in must be a single String of 12 bytes or a string of 24 hex characters");
  } else if(valid && typeof id == 'string' && id.length == 24) {
      console.log("hex string");
    return ObjectID.createFromHexString(id);
  } else if(id == null || typeof id == 'number') {
      console.log("number");
    // convert to 12 byte binary string
    this.id = this.generate(id);
  } else if(id != null && id.length === 12) {
      console.log("12 byte string");
    // assume 12 byte string
    this.id = id;
  } else if(id != null && id.toHexString) {
      console.log("duck-typing");
    // Duck-typing to support ObjectId from different npm packages
    return id;
  }

  if(ObjectID.cacheHexString) this.__id = this.toHexString();
};
```

output: 

```
56585bab66104e7300fd86df string instanceof ObjectID? false instanceof Buffer? false caller null
hex string
<Buffer 56 58 5b ab 66 10 4e 73 00 fd 86 df> 'object' 'instanceof ObjectID?' false 'instanceof Buffer?' true 'caller' [Function: createFromHexString]
12 byte string
```

first call evaluates `else if(valid && typeof id == 'string' && id.length == 24)` statement
second call evaluates `else if(id != null && id.length === 12)` statement

**Comment by hbakhtiyor** [comment]
ah, false alert, i found where's corrupted, in my project script during stripping empty key objects ))

thanks
