### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by polkhovsky** [christkv/mongodb-core#126]
This exception is crashing my app on the server:

```
TypeError: Error.captureStackTrace is not a function
    at Error.MongoError (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1i7w6an++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:13:9)
    at Function.MongoError.create (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1i7w6an++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1i7w6an++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:161:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
```

**Comment by christkv** [comment]
You are running the mongodb-core in an environment that does not have Error.captureStackTrace present (that means not node.js). You might want to reopen this with meteor instead.
