### ISSUE TITLE
Throws "RangeError: Invalid array buffer length" in version 1.3.18

### ISSUE THREAD

**Issue by abondoa** [christkv/mongodb-core#138]
I have a node js web API running in azure and using mongodb as database. It seems that we are sporadically getting the following error:

    RangeError: Invalid array buffer length
        at new ArrayBuffer (native)
        at new Uint8Array (native)
        at allocate (buffer.js:98:17)
        at new Buffer (buffer.js:49:12)
        at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\connection.js:269:29)
        at emitOne (events.js:77:13)
        at TLSSocket.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:146:16)
        at TLSSocket.Readable.push (_stream_readable.js:110:10)
        at TLSWrap.onread (net.js:523:20)

This happens approximately once or twice a day and I have not been able to replicate it on a local setup to debug further. Every time we see this error, the azure instance terminates and restarts.

**Comment by christkv** [comment]
If it's ransom like that it's going to be very hard to find out what the root problem is. however I also don't think you are using 1.3.8 as the error is at 269 in connection.js and here is the connection.js for this version

https://github.com/christkv/mongodb-core/blob/V1.3.8/lib/connection/connection.js

I would recommend upgrading first to the latest 2.2.x driver and then see if it still happening

**Comment by abondoa** [comment]
Ah sorry, version 1.3.**18**

We are looking to upgrade some other stuff anyways, and will probably also take mongo-core. I will let you know if we encounter problems with the newer version.

**Comment by christkv** [comment]
closing for now, reopen if you can identify the issue
