### ISSUE TITLE
TypeError: hex is not a function creating an ObjectID 

### ISSUE THREAD

**Issue by euribe98** [christkv/mongodb-core#155]
Hello,
I'm getting hex is not a function when trying to create an ObjectId from an existing hex string as follows:
**var newId =  new ObjectID('586ed9c2578b8212afb3fc86');**

This results in the following stack trace.  Line 52 of objectid.js producing the error is:
**return new ObjectID(Buffer.from(id, 'hex'));**

**I'm running mongodb version  v3.2.3, nodejs driver version 2.2.19 and node version v5.5.0**

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    **at new ObjectID (/Users/evan/Documents/workspace/nodejs/node_modules/bson/lib/bson/objectid.js:52:32)**
    at CollectionDriver.get (/Users/evan/Documents/workspace/nodejs/collectionDriver.js:55:18)
    at /Users/evan/Documents/workspace/nodejs/mongo.js:86:25
    at callbacks (/Users/evan/Documents/workspace/nodejs/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/evan/Documents/workspace/nodejs/node_modules/express/lib/router/index.js:135:11)
    at param (/Users/evan/Documents/workspace/nodejs/node_modules/express/lib/router/index.js:132:11)
    at param (/Users/evan/Documents/workspace/nodejs/node_modules/express/lib/router/index.js:132:11)
    at pass (/Users/evan/Documents/workspace/nodejs/node_modules/express/lib/router/index.js:142:5)

**Comment by Lukx** [comment]
We are also experiencing this on v2.1.2 of this package together with mongo v3.2.9 on Node 5.7.1. However, on node 5.12.0 and node 6.6.0 it works perfectly!

**Comment by euribe98** [comment]
Thank you Lukx. Yes, upgrading to the latest version of node fixed my issue.

**Comment by despairblue** [comment]
I think this issue should stay open, since it also occurs with node@4 (which will be supported by the foundation until April next year).

**Comment by christkv** [comment]
it should no longer affect the latest version 2.2.19
