### ISSUE TITLE
socket timeouts bubbling up to process uncaughtException

### ISSUE THREAD

**Issue by randypuro** [christkv/mongodb-core#165]
We occasionally see socket timeouts bubbling all the way up as `uncaughtExceptions` on the process using mongoose 4.7.9 with mongodb 2.2.22/mongodb-core 2.2.17. Tried using the same setup with mongodb 2.2.24/mongodb-core 2.2.18 with the same issues.

Total shot in the dark, but I'm wondering about the following lines https://github.com/christkv/mongodb-core/blob/2.0/lib/connection/pool.js#L267-L270 which show up in the stacktrace: like `error` events, should `timeout` events also map to `close` events to "not trigger the low level error handler in node"?

```
Error: connection timeout
        at Db.<anonymous> (./node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
        at emitTwo (events.js:106:13)
        at Db.emit (events.js:191:7)
        at Server.listener (./node_modules/mongodb/lib/db.js:1798:14)
        at emitOne (events.js:96:13)
        at Server.emit (events.js:188:7)
        at Server.<anonymous> (./node_modules/mongodb/lib/server.js:274:14)
        at emitOne (events.js:96:13)
        at Server.emit (events.js:188:7)
        at Pool.<anonymous> (./node_modules/mongodb-core/lib/topologies/server.js:335:12)
        at emitOne (events.js:96:13)
        at Pool.emit (events.js:188:7)
        at Connection.<anonymous> (./node_modules/mongodb-core/lib/connection/pool.js:270:12)
        at Connection.g (events.js:291:16)
        at emitTwo (events.js:106:13)
        at Connection.emit (events.js:191:7)
        at Socket.<anonymous> (./node_modules/mongodb-core/lib/connection/connection.js:185:10)
        at Socket.g (events.js:291:16)
        at emitNone (events.js:86:13)
        at Socket.emit (events.js:185:7)
        at Socket._onTimeout (net.js:339:8)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by christkv** [comment]
what kind of connection string and options are you using ?

**Comment by randypuro** [comment]
It happens for us in a couple different environments with various settings. The simplest being:

connection string:

`mongodb://localhost:27017/{dbname}?poolSize=15` connecting to mongo 3.2.8 running in docker.

with options:

`{server: {socketOptions: {keepAlive: 10000, connectTimeoutMS: 10000, socketTimeoutMS: 30000}}}`

We've tried playing with the `socketTimeoutMS` (0, unset, explicit as above) and `keepAlive` times without any luck. My best guess is that it's timing out an idle connection. It happens locally if my computer goes to sleep (which sort of makes sense except for the error bubbling all the way to the top rather than just causing a reconnect), but also flakily, but regularly, on CI in the midst of an active test suite doing active operations (same stack trace, same connection string/options, also against docker).

I hope that helps.

**Comment by christkv** [comment]
Hi Randy

It seems Mongoose is the culprit here as it's re-emitting it as an error.

https://github.com/Automattic/mongoose/blob/bef9d78fac2482a28e33c485842cb1f7fb05837f/lib/drivers/node-mongodb-native/connection.js#L170

Do you mind filing a ticket with mongoose referencing this issue to see what they say.

**Comment by randypuro** [comment]
Ok, happy to try that, although there's something else weird going on here. Sometimes when these timeouts occur, it appears that connections aren't being recreated in a healthy way - I'm seeing subsequent requests just hang before returning which is strange. I'll see 120sec responses to really simple db queries. I'm also wondering in general what consumers of the library (like mongoose) are meant to do with the `timeout` events? Are they just there to detect potential issues? We're presuming that the pool should re-establish healthy connections somewhat transparently?

**Comment by christkv** [comment]
Timeouts are not errors as the driver will attempt to reconnect. There seems to be some sort of logical issues here.

**Comment by christkv** [comment]
going to close as it's a mongoose issue
