### ISSUE TITLE
Error: write after end (Connection.write)

### ISSUE THREAD

**Issue by peterpme** [christkv/mongodb-core#174]
Hi,

Thanks for putting together this awesome library! Lately I've been noticing a `Error: write after end` error popping up. I haven't been able to figure out a reproduction source.

Node 7.7.4
Mongoose 4.9.2

(KeystoneJS 4.0.0-beta.5)
```
0|bootler- | Error: write after end
0|bootler- |     at writeAfterEnd (_stream_writable.js:191:12)
0|bootler- |     at Socket.Writable.write (_stream_writable.js:238:5)
0|bootler- |     at Socket.write (net.js:673:40)
0|bootler- |     at Connection.write (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:518:54)
0|bootler- |     at /home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:205:16
0|bootler- |     at Object.cb (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/auth/mongocr.js:95:9)
0|bootler- |     at Connection.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:245:32)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitTwo (events.js:106:13)
0|bootler- |     at Connection.emit (events.js:194:7)
0|bootler- |     at Socket.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:185:10)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitNone (events.js:86:13)
0|bootler- |     at Socket.emit (events.js:188:7)
0|bootler- |     at Socket._onTimeout (net.js:354:8)
0|bootler- |     at ontimeout (timers.js:380:14)
0|bootler- |     at tryOnTimeout (timers.js:244:5)
0|bootler- |     at Timer.listOnTimeout (timers.js:214:5)
0|bootler- | logging error with Opbeat: { uuid: 'b89a6c7f-3e8f-469b-8d23-f39b149176e5' }
0|bootler- | Error: write after end
0|bootler- |     at writeAfterEnd (_stream_writable.js:191:12)
0|bootler- |     at Socket.Writable.write (_stream_writable.js:238:5)
0|bootler- |     at Socket.write (net.js:673:40)
0|bootler- |     at Connection.write (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:518:54)
0|bootler- |     at /home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:205:16
0|bootler- |     at Object.cb (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/auth/mongocr.js:95:9)
0|bootler- |     at Connection.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:245:32)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitTwo (events.js:106:13)
0|bootler- |     at Connection.emit (events.js:194:7)
0|bootler- |     at Socket.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:185:10)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitNone (events.js:86:13)
0|bootler- |     at Socket.emit (events.js:188:7)
0|bootler- |     at Socket._onTimeout (net.js:354:8)
0|bootler- |     at ontimeout (timers.js:380:14)
0|bootler- |     at tryOnTimeout (timers.js:244:5)
0|bootler- |     at Timer.listOnTimeout (timers.js:214:5)
0|bootler- | Error: write after end
0|bootler- |     at writeAfterEnd (_stream_writable.js:191:12)
0|bootler- |     at Socket.Writable.write (_stream_writable.js:238:5)
0|bootler- |     at Socket.write (net.js:673:40)
0|bootler- |     at Connection.write (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:518:54)
0|bootler- |     at /home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:205:16
0|bootler- |     at Object.cb (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/auth/mongocr.js:95:9)
0|bootler- |     at Connection.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:245:32)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitTwo (events.js:106:13)
0|bootler- |     at Connection.emit (events.js:194:7)
0|bootler- |     at Socket.<anonymous> (/home/app/cms/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:185:10)
0|bootler- |     at Object.onceWrapper (events.js:293:19)
0|bootler- |     at emitNone (events.js:86:13)
0|bootler- |     at Socket.emit (events.js:188:7)
0|bootler- |     at Socket._onTimeout (net.js:354:8)
0|bootler- |     at ontimeout (timers.js:380:14)
0|bootler- |     at tryOnTimeout (timers.js:244:5)
0|bootler- |     at Timer.listOnTimeout (timers.js:214:5)
```

Thanks again!

**Comment by peterpme** [comment]
After digging around the library, I think I've found the culprit here:
https://github.com/christkv/mongodb-core/blob/2.0/lib/connection/connection.js#L521

I'm wondering if this has to do an interrupted connection on my end or if the issue has to do with the fact that the connection is ending before the socket is written via `net`. 

Thanks again!

**Comment by christkv** [comment]
This is the typical error if a socket was closed for some reason (running out of file descriptors, network hickup, etc) and not a driver bug.

**Comment by peterpme** [comment]
Hey @christkv thanks for the quick reply! Any chance you can point me in the right direction? I'm at a loss for how I can fix this and it's been coming up frequently. 

Thanks again!

**Comment by christkv** [comment]
It seems to be happening in the auth process and you seem to be running mongocr auth. Are you using a very old MongoDb server ?

**Comment by christkv** [comment]
can you post the package.json in /home/app/cms/node_modules/mongoose/node_modules/mongodb-core

**Comment by peterpme** [comment]
Hey,

I don't think so. I'm running the master build of [Keystone with Mongoose 4.9.2](https://github.com/keystonejs/keystone/blob/master/package.json#L62)
```
{
  "name": "mongodb-core",
  "version": "2.1.9",
  "description": "Core MongoDB driver functionality, no bells and whistles and meant for integration not end applications",
  "main": "index.js",
  "scripts": {
    "test": "node test/runner.js -t functional",
    "coverage": "node_modules/.bin/nyc node test/runner.js -t functional -l && node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls",
    "lint": "eslint lib"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/christkv/mongodb-core.git"
  },
  "keywords": [
    "mongodb",
    "core"
  ],
  "dependencies": {
    "bson": "~1.0.4",
    "require_optional": "~1.0.0"
  },
  "devDependencies": {
    "co": "^4.5.4",
    "coveralls": "^2.11.6",
    "es6-promise": "^3.0.2",
    "gleak": "0.5.0",
    "integra": "0.1.8",
    "jsdoc": "3.3.0-alpha8",
    "mkdirp": "0.5.0",
    "mongodb-topology-manager": "1.0.x",
    "mongodb-version-manager": "christkv/mongodb-version-manager#master",
    "nyc": "^5.5.0",
    "optimist": "latest",
    "rimraf": "2.2.6",
    "semver": "4.1.0"
  },
  "peerOptionalDependencies": {
    "kerberos": "~0.0",
    "bson-ext": "1.0.5"
  },
  "author": "Christian Kvalheim",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/christkv/mongodb-core/issues"
  },
  "homepage": "https://github.com/christkv/mongodb-core"
}
```

**Comment by christkv** [comment]
Then I suggest looking at if you have enough file descriptors  for the number of sockets you are opening and dropping down to node 6 to see if you are running into a node issue. Really should not run 7 for anything that is planned for production as it's unstable

**Comment by peterpme** [comment]
Gotcha, thanks again for your help!
