### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by tiefenb** [christkv/mongodb-core#45]
I get often an error and can't find a solution. It happens in the mongodb-core module from mongojs...

2015-09-08T06:15:02.883564+00:00 app[worker.1]: /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:757
2015-09-08T06:15:02.883591+00:00 app[worker.1]: catch(err) { process.nextTick(function() { throw err}); }
2015-09-08T06:15:02.883593+00:00 app[worker.1]: ^
2015-09-08T06:15:02.883595+00:00 app[worker.1]: 
2015-09-08T06:15:02.883596+00:00 app[worker.1]: TypeError: cb is not a function
2015-09-08T06:15:02.883598+00:00 app[worker.1]: at /app/node_modules/mongojs/lib/collection.js:131:7
2015-09-08T06:15:02.883599+00:00 app[worker.1]: at /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/replset.js:371:5
2015-09-08T06:15:02.883601+00:00 app[worker.1]: at /app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:756:13
2015-09-08T06:15:02.883602+00:00 app[worker.1]: at Callbacks.emit (/app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:95:3)
2015-09-08T06:15:02.883604+00:00 app[worker.1]: at null.messageHandler (/app/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:243:23)
2015-09-08T06:15:02.883606+00:00 app[worker.1]: at Socket. (/app/node_modules/mongojs/node_modules/mongodb-core/lib/connection/connection.js:262:22)
2015-09-08T06:15:02.883608+00:00 app[worker.1]: at emitOne (events.js:77:13)
2015-09-08T06:15:02.883609+00:00 app[worker.1]: at Socket.emit (events.js:169:7)
2015-09-08T06:15:02.883610+00:00 app[worker.1]: at readableAddChunk (_stream_readable.js:146:16)
2015-09-08T06:15:02.883612+00:00 app[worker.1]: at Socket.Readable.push (_stream_readable.js:110:10)
2015-09-08T06:15:02.883613+00:00 app[worker.1]: at TCP.onread (net.js:523:20)

**Comment by christkv** [comment]
you should open this ticket in mongojs and provide a test case as it's saying you did not pass in a valid callback function.
