### ISSUE TITLE
Newer version of mongodb-core now failing to build C extensions?

### ISSUE THREAD

**Issue by shakefu** [christkv/mongodb-core#46]
C-extensions used to work for both OS X (10.9) and Ubuntu 12.04... now I get this:

```
$ npm install mongodb-core
/
> kerberos@0.0.14 install /Users/jalheid/tmp/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/kerberos.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jalheid/tmp/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
mongodb-core@1.2.12 node_modules/mongodb-core
├── bson@0.4.11
└── kerberos@0.0.14 (nan@2.0.9)
```

Any ideas?

**Comment by AndrewKeig** [comment]
:+1:

**Comment by christkv** [comment]
it looks like your gcc environment is hosed

ld: library not found for -lgcc_s.10.5

It only requires the MIT kerberos library and headers installed so if it's not building something is wrong with the build environment. You might want to try to build node itself to see if it even passes or get the repository and try to build it locally.

**Comment by christkv** [comment]
closed due to inaction
