### ISSUE TITLE
MongoError when using mongos

### ISSUE THREAD

**Issue by alexkwolfe** [christkv/mongodb-core#52]
I recently upgraded from 1.2.14 to 1.2.19 and immediately starting seeing MongoErrors. I'm connecting to sharded MongoDB 3.0.5 (using mongos). When I reconfigured the connection to skip mongos and connect straight to a replica set master, the errors stopped.

After some trial and error I found that 5f4cf95 seems to be the culprit. Using the commit immediately preceding this one, these errors do not occur. I am using `readPreference: 'secondaryPreferred'`.

Here are the two varieties of MongoError that I see

```
MongoError: Can't canonicalize query: BadValue unknown top level operator: $query
    at Function.MongoError.create (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:267:34)
    at Callbacks.emit (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)

MongoError: Can't canonicalize query: BadValue unknown top level operator: $maxTimeMS
    at Function.MongoError.create (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:267:34)
    at Callbacks.emit (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (./api/releases/20151023195307/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
```

**Comment by christkv** [comment]
Are you using mongodb-core directly ? can you provide a simple code example that reproduces it.

**Comment by alexkwolfe** [comment]
No. I'm using the mongodb package, which recently had its dependency on mongodb-core updated.

```javascript
var MongoClient = require('mongodb').MongoClient;
var url = 'mongodb://mongo/test?readPreference=secondaryPreferred';

MongoClient.connect(url, {}, function(err, db) {
  if (err) throw err;
  var options = { sort: [['_id', 'descending']] };
  db.collection('documents').findOne({}, options, function(err, doc){
    if (err) throw err;
    console.log(doc)
  })
});
```

The above code results in the following error: 
```
MongoError: Can't canonicalize query: BadValue unknown top level operator: $query
    at Function.MongoError.create (node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
```

If I remove the sort option, or set `readPreference=primary`, the error no longer occurs.

**Comment by christkv** [comment]
29de00425c5a2ecdf60e39c670d2f9201ce9d8c3 fixes the issue
