### ISSUE TITLE
*URGENT* *BUG* MongoDB 3.2 An unknown error has occurred

### ISSUE THREAD

**Issue by niftylettuce** [christkv/mongodb-core#68]
I added in <https://github.com/christkv/mongodb-core/blob/master/lib/topologies/server.js#L251> a `console.error('err', err);` and this was the actual error.  Otherwise it only tells me "An unknown error has occurred" it doesn't tell me "cannot read property id of undefined".  This is a definite error.  I'm on MongoDB v3.2.

```log
[TypeError: Cannot read property 'id' of undefined]
error: An unknown error has occured, please try again response_time=43, path=/admin/stock, page=1, limit=10, , , status=302, response_type=text/html; charset=utf-8, type=api_error, message=An unknown error has occured, please try again, stack=MongoError: An unknown error has occured, please try again
    at null.messageHandler (/Users/foobar/Public/foobar/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:29)
    at Socket.<anonymous> (/Users/foobar/Public/foobar/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by niftylettuce** [comment]
I am using a $lookup operation here, its erroring out as well.

**Comment by niftylettuce** [comment]
I think it needs fixed like this:

```diff
-state.callbacks.flush(new MongoError(err));
if (_.isError(err))
  state.callbacks.flush(err);
else
  state.callbacks.flush(new MongoError(err));
```

This is because `err` in this `try catch` block can sometimes already be a `MongoError` error object per the following example:

```log
{ [MongoError: TypeError: Cannot read property 'id' of undefined]
  name: 'MongoError',
  message: [TypeError: Cannot read property 'id' of undefined] }
```

**Comment by niftylettuce** [comment]
Anyways, I'm still not sure why we're getting this "Cannot read property `id` of undefined" issue.

**Comment by christkv** [comment]
Sorry I don't know what version of the driver you are using. Would it be possible for you to upgrade to the latest and try again. I will have a look at your suggested fix once I get back from christmas vacation. Any more context provided would be helpful including how to reproduce.

**Comment by joshualo** [comment]
I am seeing this error on 3.2 but not on 3.0.  The model that is throwing the error has a custom String _id.

**Comment by christkv** [comment]
@joshualo with what driver version and can you produce code and post it here that reproduces.

**Comment by joshualo** [comment]
@christkv node driver 2.0.46.  I think I captured most the code.  Basically the syncWithExternal pulls a list of people (assume unique names), sets _id to name, updates or upserts them into db, also populating a cached list.  The init function is used to populate the cached list from scratch.  syncWithExternal works but we get the error when calling init.

Error:

    MongoError: TypeError: Cannot read property 'id' of undefined

Code:

    var schema = new mongoose.Schema({
      _id: {type: String, index: true},
      name: {type: String, required: true}
    });

    var personList = {};

    schema.statics.initList = function(callback) {
      callback = callback || _.noop;

      this.find({}).exec((err, people) => {
        if (err) {
          console.log(err);
          return callback(err);
        }

        if (!people) {
          return callback(new Error());
        }

        for (var i = 0; i < people.length; i++) {
          var person = people[i];
          personList[person.name] = person;
        }

        callback();
      });
    }

    schema.statics.syncWithExternal = function(callback) {
      callback = callback || _.noop();

      var people = someExternalDataSource.toJSON();

      var update = (person, callback) => {
        if (!person.name) {
          return callback();
        }

        person._id = person.name;
        this.findByIdAndUpdate(person._id, person, {upsert: true, new: true}, function(err, person) {
          if (err) {
            return callback(err);
          }

          personList[person._id] = person;
        });
      }

      var finished = err => {
        return callback(err);
      }

      async.each(people, update, finished);
    };

**Comment by christkv** [comment]
You might need to open a mongoose ticket for this one. But I would update mongoose first if you are on the 4.x branch first to get the latest node driver with official 3.2 support.

**Comment by niftylettuce** [comment]
If `id` is missing it's because Mongoose 3.8 added it as a virtual and
you're using it with lean or something?

**Comment by christkv** [comment]
no further response, closing due to inactivity
