### ISSUE TITLE
Invalid peer dependency 'kerberos' reported from npm-shrinkwrap

### ISSUE THREAD

**Issue by bsleighb** [christkv/mongodb-core#73]
I'm trying to run `npm shrinkwrap` on my project and the error I'm getting is: 
```
peer invalid: kerberos@~0.0, required by mongodb-core@1.2.32
```

And here's the full `npm-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/bsleighb/.nvm/versions/node/v5.5.0/bin/node',
1 verbose cli   '/Users/bsleighb/.nvm/versions/node/v5.5.0/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack peer invalid: kerberos@~0.0, required by mongodb-core@1.2.32
4 verbose stack     at shrinkwrap_ (/Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/deps.js:123:5
4 verbose stack     at LOOP (/Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/deps.js:123:5
4 verbose stack     at LOOP (/Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/bsleighb/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /Users/bsleighb/Repositories/Dayzbuddy
6 error Darwin 15.3.0
7 error argv "/Users/bsleighb/.nvm/versions/node/v5.5.0/bin/node" "/Users/bsleighb/.nvm/versions/node/v5.5.0/bin/npm" "shrinkwrap"
8 error node v5.5.0
9 error npm  v3.3.12
10 error Problems were encountered
10 error Please correct and try again.
10 error peer invalid: kerberos@~0.0, required by mongodb-core@1.2.32
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by christkv** [comment]
you can try the brand new 2.1.5 that uses my own https://www.npmjs.com/package/require_optional module to allow for peerOptionalDependencies in the package.json.
