### ISSUE TITLE
[Question] How to handle a 'network error'?

### ISSUE THREAD

**Issue by iamdoron** [christkv/mongodb-core#80]
I'm using the mongodb nodejs driver (which uses mongoldb-core v1.3.1), and from time to time I get the following error: 

```
MongoError: network error while attempting to run command 'findandmodify' on host 'x.x.x.x:xxxxx'
    at Function.MongoError.create (./node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (./node_modules/mongodb-core/lib/topologies/server.js:929:66)
    at Callbacks.emit (./node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at null.messageHandler (./node_modules/mongodb-core/lib/topologies/server.js:282:23)
    at TLSSocket.<anonymous> (./node_modules/mongodb-core/lib/connection/connection.js:273:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

How should a network error be handled? what does it mean?
How can I further investigate this network issue? I want to minimize it, but I'm not sure what exactly went wrong. Is there a more detailed version of the error I can somehow get?

BTW, I'm connecting to mongos via TLS (as you can see in the stacktrace)

**Comment by christkv** [comment]
Well nothing the driver can do around this, this is mongos not being able to apply the findAndModify operation to one of the shards. I suspect you have unstable networks between the mongos proxy and the shards. I would ask for help at the google mongodb user group or look at the commercial support options we offer.
