### ISSUE TITLE
MongoError: no mongos proxy available

### ISSUE THREAD

**Issue by iamdoron** [christkv/mongodb-core#88]
Hi,

We've been using mongodb 2.1.7 (mongodb-core 1.3.1) for a month, we had no similar issues. Today we've updated to the latest version (mongodb 2.1.11, mongoldb-core 1.3.10), and we got the following errors (constantly happened in our production servers, we had to rollback the version):

```
MongoError: no mongos proxy available
   at State.pickServer (server/node_modules/mongodb-core/lib/topologies/mongos.js:268:33)
   at Mongos.getServer (server/node_modules/mongodb-core/lib/topologies/mongos.js:858:29)
   at nextFunction (server/node_modules/mongodb-core/lib/cursor.js:513:35)
   at Cursor.next [as _next] (server/node_modules/mongodb-core/lib/cursor.js:655:3)
   at nextObject (server/node_modules/mongodb/lib/cursor.js:654:8)
   at Cursor.next (server/node_modules/mongodb/lib/cursor.js:258:12)
   at Cursor._read (server/node_modules/mongodb/lib/cursor.js:1043:8)
   at Readable.read (_stream_readable.js:328:10)
   at resume_ (_stream_readable.js:718:12)
   at doNTCallback2 (node.js:441:9)
   at process._tickDomainCallback (node.js:396:17)
```

```
MongoError: no mongos proxy available
    at State.pickServer (server/node_modules/mongodb-core/lib/topologies/mongos.js:268:33)
    at executeWriteOperation (server/node_modules/mongodb-core/lib/topologies/mongos.js:1150:32)
    at Mongos.update (server/node_modules/mongodb-core/lib/topologies/mongos.js:634:3)
    at Mongos.update (server/node_modules/mongodb/lib/mongos.js:371:17)
    at updateDocuments (server/node_modules/mongodb/lib/collection.js:1003:19)
    at updateOne (server/node_modules/mongodb/lib/collection.js:856:3)
    at Collection.updateOne (server/node_modules/mongodb/lib/collection.js:841:44)
    at Provider.saveSyncTime (server/node_modules/clients-repo/providerRepo.js:596:18)
    ...
```

**Comment by christkv** [comment]
I'm not sure I understand this, you were using 2.1.7 and upgraded to 2.1.7 ?

**Comment by iamdoron** [comment]
sorry, I meant 2.1.11

**Comment by christkv** [comment]
what does you connection settings look like ?

**Comment by christkv** [comment]
and what kind of operations volume do you have ?

**Comment by iamdoron** [comment]
`mongodb://mongos-server01:port,mongos-server02:port/production?ssl=true`

It happened during a background job with ~50k operations. They were spread out in bulk operations with ~3k operations for each bulk

**Comment by christkv** [comment]
Alright 2.1.12 released which has some improvements in handling of mongos. You also want to know about the option acceptableLatencyMS that controls the latency window for selecting mongos proxies. It default to 15 ms.

If no proxies fulfill the latency window in-between operations it sorts the proxies by it's last ismaster call time and returns the first one. You should probably set the latencyWindow to a higher value to ensure proper load balancing as it's likely that under load the latency window will increase.

**Comment by iamdoron** [comment]
thanks, it seems like this issue has been resolved (no problems with the new version)
