### ISSUE TITLE
Cannot read property 's' of null on 1.3.17

### ISSUE THREAD

**Issue by iamruinous** [christkv/mongodb-core#95]
Upgraded to the latest `mongodb-core` by way of `mongojs` and started getting lots of errors.

```
/usr/src/app/node_modules/mongodb-core/lib/cursor.js:285
pool = server.s.pool;
^
TypeError: Cannot read property 's' of null
at [object Object].Cursor._getmore (/usr/src/app/node_modules/mongodb-core/lib/cursor.js:285:18)
at nextFunction (/usr/src/app/node_modules/mongodb-core/lib/cursor.js:602:12)
at [object Object].Cursor.next [as _next] (/usr/src/app/node_modules/mongodb-core/lib/cursor.js:689:3)
at nextObject (/usr/src/app/node_modules/mongodb/lib/cursor.js:658:8)
at [object Object].Cursor.next (/usr/src/app/node_modules/mongodb/lib/cursor.js:262:12)
at /usr/src/app/node_modules/mongojs/lib/cursor.js:36:14
at apply (/usr/src/app/node_modules/thunky/index.js:16:28)
at [object Object]._get (/usr/src/app/node_modules/thunky/index.js:27:3)
at [object Object].Cursor.next (/usr/src/app/node_modules/mongojs/lib/cursor.js:30:8)
at Immediate.loop [as _onImmediate] (/usr/src/app/node_modules/mongojs/lib/cursor.js:57:10)
at tryOnImmediate (timers.js:534:15)
at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by christkv** [comment]
Can your provide a reproduction script that causes this. Is it possible you closed the server connection before the query is finished ?

**Comment by christkv** [comment]
please test against 1.3.18 and let me know
